name: Patch Nerd Fonts

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for font patching'
        required: false
        default: 'Manual font patch'

jobs:
  patch-fonts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p ${{ github.workspace }}/myFontsOut

      - name: Patch Fonts with Nerd Fonts Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/myFonts:/in:Z \
            -v ${{ github.workspace }}/myFontsOut:/out:Z \
            nerdfonts/patcher --mdi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nerd-fonts
          path: ${{ github.workspace }}/myFontsOut/
          retention-days: 90
