name: Manually Trigger Font Patching

on:
  workflow_dispatch:
    # 手动触发工作流
    inputs:
      reason:
        description: 'Reason for font patching'
        required: false
        default: 'Manual font patch'

jobs:
  patch-fonts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontforge python3-pip
          pip install python-fontforge argparse
      
      - name: Patch Fonts
        run: |
          mkdir -p patched_fonts
          
          # 处理 myFonts 目录下的所有 .ttf 字体
          for font in myFonts/*.otf; do
            fontforge -script font-patcher "$font" --mdi -out patched_fonts
          done
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nerd-fonts
          path: patched_fonts/
          # 保留 90 天
          retention-days: 90
